netbox:
  netboxhost: '100.80.37.100'
  netboxapitoken: '12014e6103f9364f3c65a60e260995beedafff4c'

targets:
  - vrf: NOSI
    subnets:
      - 192.168.1.0/25
  - vrf: NUAGE_VDOM
    subnets:

scanthreads: 20
